[versions]

[libraries]
annotations = "org.jetbrains:annotations:26.0.2-1"
junit-bom = "org.junit:junit-bom:6.0.2"
junit-jupiter = { module = "org.junit.jupiter:junit-jupiter" }
junit-platform = { module = "org.junit.platform:junit-platform-launcher" }

[bundles]
junit = ["junit-jupiter", "junit-platform"]

[plugins]
publisher = "com.vanniktech.maven.publish:0.36.0"
